### ISSUE TITLE
Is there any way to put normalization in the initial state profile obtained from IPGlasma ? 

### ISSUE THREAD

**Issue by nikhilhatwar** [schenke/ipglasma#13]
I am using IPGlasma initial state profile with your JETSCAPE framework. Like in the case of TRENTo, is there any parameter to introduce a normalization factor in the initial state profile from IPGlasma?

**Comment by hejajama** [comment]
You can change the QsmuRatio parameter in the input file: smaller values correspond to larger saturation scales=larger densities.
